/**
 * Base de conocimiento de TKOC Intelligence para el asistente de IA (TKOC AI).
 *
 * Es texto estático que se inyecta como bloque de sistema (cacheable) en
 * /api/ai/chat. Está derivada del código de la plataforma: rutas del
 * (dashboard), sidebar, crons de src/instrumentation.ts, libs de
 * inteligencia, src/lib/metrics.ts + src/lib/campaign-overview.ts (fuente
 * única de cálculo), src/lib/emv.ts, src/lib/creator-baseline.ts,
 * src/lib/report-config.ts, src/components/campaign-report.tsx,
 * src/app/api/campaigns/[id]/export/route.ts y src/i18n/translations.ts.
 * Mantenerla FACTUAL: si una función cambia en el código, actualizar aquí.
 * No describir funcionalidades que no existan.
 *
 * Definiciones vinculantes (David, 2026-09-05): ver la sección 5. Cualquier
 * cifra de campaña que el asistente comente sale de computeCampaignOverview;
 * el asistente NUNCA recalcula con fórmulas propias.
 *
 * Decisión 4A (David, 2026-09-05, sustituye a 4C): la tasa de engagement y el
 * CPM real se calculan SOLO sobre audiencia real (alcance → impresiones →
 * vistas). La audiencia estimada es informativa, va aparte y etiquetada, y en
 * el informe es una línea que la PM puede ocultar. Sin base real → "Sin dato
 * real", nunca una cifra inventada. Ninguna frase de esta guía puede decir que
 * la ER usa audiencia estimada.
 */

export const PLATFORM_KNOWLEDGE = `
# TKOC Intelligence — Guía de uso de la plataforma

## 1. Qué es
TKOC Intelligence es la plataforma interna de la agencia TKOC (DAMA Platforms S.L.) para gestionar campañas de influencer marketing en Instagram, TikTok y YouTube: descubrir creadores, planificar campañas, negociar fees con datos de mercado, capturar automáticamente el contenido publicado por los creadores de cada campaña, medirlo con una única definición de métricas y generar informes para el cliente.
- URL: https://intelligence.thekingofcontent.agency
- Idiomas de la interfaz: español (por defecto) e inglés. El idioma se cambia en Ajustes.
- Tema claro/oscuro: botón de luna/sol en la parte inferior de la barra lateral.
- Moneda: todo en euros (formato español "12.345 €", o "8,5 K €" en tarjetas compactas). No existen cifras en dólares.

## 2. Roles de usuario
- ADMIN: acceso completo (campañas, creadores, marcas, integraciones, benchmarks, equipo, ajustes).
- EMPLOYEE: gestiona campañas, creadores, pipeline, listas, contactos. No gestiona integraciones ni benchmarks (solo ADMIN).
- BRAND (cliente): solo lectura. Vive confinado en el Portal de cliente (/portal); cualquier otra ruta le redirige al portal. Nunca ve fees, coste, CPM, Ratio EMV, EMV Básico, CPA ni ROAS (sección 11).
- CREATOR: dashboard propio simplificado (Mi Perfil, Mi Creator Score, Mi Valor de Mercado, Mis Campañas) y Ajustes.
Los usuarios se invitan desde Ajustes → Equipo (roles Admin, Employee o Brand). El invitado recibe un email con un enlace /invite/[token] para crear su contraseña.
El asistente de IA (TKOC AI) solo está disponible para el equipo de la agencia (ADMIN y EMPLOYEE); los usuarios Brand y Creator no lo tienen.

## 3. Navegación (barra lateral) y qué hace cada página
Navegación principal:
- Inicio (/dashboard): saludo, KPIs globales (Campañas Activas, Total Influencers, Alcance Total, Engagement Medio), estado de campañas, estado de envíos, actividad reciente, accesos rápidos (Crear Campaña, Analizar Perfil, Buscar Creadores, Gestionar Listas). Aviso "Conecta tus cuentas" si no hay integraciones. Cada campaña se valora con la fuente única de cálculo (sección 5) y el panel solo suma: "Alcance Total" es la audiencia total (real + estimada, cifra informativa) de la sección 5, "Engagement Medio" sale de la tasa de engagement sobre audiencia REAL de cada campaña, y una publicación que vive en varias campañas cuenta una sola vez a nivel de agencia (el panel descuenta los duplicados). La tarjeta EMV lleva como subtítulo el Ratio EMV (solo agencia).
- Marcas (/brands): marcas/clientes. Crear marca (nombre, sitio web), asignar empleados ("Gestionar Empleados"), vincular un "Usuario Marca (solo lectura)" para que vea resultados en el portal, "Copiar link de conexión IG" (enlace para que el cliente conecte su Instagram Business sin tener cuenta), "Ver campañas".
- Campañas (/campaigns): listado con búsqueda, filtros por estado (activa / pausada / archivada) y tipo; KPIs (Campañas Activas, Perfiles Rastreados, Total Campañas, Media Encontrada). Botón "Nueva Campaña".
- Creadores (/discover): buscador de creadores con dos modos: "Base de datos" (búsqueda interna instantánea, ~10 s, por nombre/@usuario/bio, categoría, ciudad/provincia, país, seguidores, engagement mínimo, nivel de encaje con España) y "Buscar en vivo" (Apify: por @usuario o por categoría/hashtag, tarda 1-2 min). También "Pegar lista de handles" (detecta @usuarios o URLs pegados en bloque y los procesa con "Procesar todos"). Acciones por resultado: Ver perfil, Añadir a lista, Enriquecer perfiles.
- Pricing (/pricing): Calculadora de Precios independiente (no requiere campaña). Ver sección 16.
- Resultados (/compare): Comparar Campañas. Seleccionar 2 o 3 campañas y ver lado a lado: Influencers, Publicaciones, Alcance Total (= audiencia total, real + estimada, informativa), Engagements (= interacciones), Tasa Engagement (sobre audiencia REAL; "—" sin dato real), Vistas Totales, Coste Total, EMV (Ampliado) y Ratio EMV, más el reparto por tiers de influencers (en esta pantalla los tiers se agrupan Nano < 10K, Micro 10-100K, Mid 100-500K, Macro 500K-1M, Mega > 1M). Las definiciones son las de la sección 5.
- Metodología (/methodology): documentación de la metodología TKOC en 6 secciones desplegables: Planificar, Elegir, Pagar, Ejecutar, Medir y Métricas clave; etiquetas de publicidad "Colaboración pagada", "Contenido de marca". Algunos textos de esa página son anteriores a las definiciones vigentes (ejemplos en dólares, "ROI real", ER de campaña "sobre views o reach"): para cualquier fórmula mandan las definiciones de la sección 5 de esta guía y la moneda es siempre el euro.
Navegación secundaria:
- Listas (/lists): listas de creadores (crear, fijar, eliminar; alcance combinado, con email; exportar). Cada lista se abre en /lists/[id].
- Similares (/lookalikes): introduce un @handle de Instagram, TikTok o YouTube y obtiene creadores parecidos. Ver sección 17.
- Contactos (/contacts): CRM ligero de creadores con los que se ha trabajado (estado, notas, tags, teléfono, email). Se llena al añadir creadores a campañas y listas.
- Mi Base de Clientes (/client-base): ver sección 18.
- Pipeline (/pipeline): kanban global de todos los creadores de todas las campañas (filtrable por campaña) con los 8 estados. Arrastrar entre columnas cambia el estado.
- Ajustes (/settings): pestañas Perfil, Equipo, Integraciones, Benchmarks (solo ADMIN) y Facturación. Idioma y foto de perfil en Perfil.
Otras páginas sin entrada en la barra lateral:
- Analizar Perfil (/analyze): pega la URL o @handle de Instagram, TikTok o YouTube → estadísticas del creador (seguidores, engagement, medianas de likes/comentarios/vistas, desglose de contenido, frecuencia de publicación, mejor tipo de contenido, mejor hora, tendencia de engagement, calidad de audiencia), "Obtener Insights", "Buscar Similares", "Añadir a lista", "Tarjeta de Tarifas" (guardar tarifa estándar del creador).
- Ficha de creador (/creators/[id]).
- Calendario (/calendar): vista mensual de campañas por fechas.
- Knowledge Base (/knowledge-base): documento interno de referencia.
- Informe de campaña (/campaigns/[id]/report): ver sección 10.
Notificaciones: campana en la parte inferior de la barra lateral (nuevos posts detectados, creadores añadidos, etc.).

## 4. Flujo de trabajo de una campaña (paso a paso para el PM)

### Paso 1 — Crear la campaña
Campañas → "Nueva Campaña" (/campaigns/new). Opcional: "Cargar desde plantilla" para pre-rellenar. Campos:
1. Marca / Cliente (opcional pero recomendado): selecciona la marca. Si no existe, "Crear una marca primero" en Marcas. La marca es lo que permite que el cliente vea la campaña en su portal.
2. Tipo de campaña: "Seguimiento de Influencers" (rastrea creadores concretos: posts, reels, stories), "Social Listening" (rastrea a todos los que mencionan la marca o hashtags) o "Campaña UGC" (gestión de creadores UGC, pagos y entrega de contenido, sin calculadora de CPM).
3. Objetivo de la campaña (OBLIGATORIO; opcional solo en Social Listening): Notoriedad/Awareness, Engagement/Interacción, Tráfico web, Conversión/Ventas o Contenido/UGC. Determina con qué números se juzga la campaña y condiciona la Inteligencia de Campaña y la Sugerencia de Creator Mix.
4. Objetivos numéricos (OBLIGATORIO al menos uno mayor que 0; opcional solo en Social Listening): Vistas, Alcance, Interacciones, ER objetivo (%) y/o CPM máximo (€ por 1.000 vistas). La interfaz sugiere cuáles son los recomendados según el objetivo. Sin objetivo o sin al menos un objetivo numérico el servidor rechaza la creación con un mensaje claro ("Selecciona un objetivo y al menos un objetivo numérico para crear la campaña"). Detalle en la sección 6.
5. Nombre (ej. "Vileda Primavera 2026").
6. Cuentas de Marca Objetivo: @menciones (ej. @vileda.es) y #hashtags a rastrear. Se pueden añadir varios.
7. Plataformas: Instagram, TikTok, YouTube.
8. Filtro de País (opcional): solo rastrear contenido de creadores de ese país; vacío = mundial.
9. Tipo de pago: Campaña de Pago (los creadores cobran) o Campaña Gifted (reciben producto). Las UGC siempre son de pago.
10. Duración: Fecha de Inicio y Fecha de Fin, o "Siempre Activo" (sin fecha de fin). SOLO se captura contenido publicado dentro de estas fechas.
11. Brief (texto y adjuntos PDF/Word/Excel/imagen) — también se puede añadir después en la pestaña Planificar.
También existe el "Asistente de Campaña" (wizard de 4 pasos: objetivo → lo esencial → qué rastrear → revisar y lanzar) accesible desde el listado de campañas.
Después de crear, cualquier campaña puede guardarse como plantilla ("Guardar como plantilla") y editarse ("Editar Campaña" en la pestaña Aprender). Si los objetivos ya están congelados, cada cambio de objetivo numérico queda registrado con su motivo (sección 6).

### Paso 2 — Añadir creadores (pestaña "Elegir")
Cada campaña (/campaigns/[id]) tiene 5 pestañas que siguen la metodología: Planificar, Elegir, Pagar, Ejecutar, Aprender.
Formas de añadir creadores a la campaña:
- Desde la propia pestaña Elegir: buscar por username en la base de datos, o "Añadir Creador UGC" pegando @handle o URL de perfil (se analiza el perfil con Apify y se añade).
- "Añadir varios" (botón en la pestaña Elegir, junto al buscador) — LA FORMA DE AÑADIR MUCHOS DE GOLPE A UNA CAMPAÑA: se abre un panel con "Pegar lista" (pega @usuarios o URLs de perfil de Instagram/TikTok/YouTube, uno por línea o separados por comas) y "O sube un CSV" (se usa la primera columna, o cualquier celda con @ o URL; la fila de cabecera se ignora). Opcional: "Plataforma (si la URL no la indica)". Hasta 200 creadores por tanda. Los que ya están en la base de datos se añaden al instante; los nuevos se analizan con Apify (de 3 en 3) y los repetidos se omiten. Al terminar muestra añadidos / omitidos / errores por handle.
- Desde Creadores (/discover): buscar en la base de datos interna o en vivo y usar "Añadir a..." → campaña o lista. "Pegar lista de handles" sirve para descubrir/analizar muchos perfiles a la vez.
- Desde Similares (/lookalikes) o Analizar Perfil: "Añadir a lista" / "Añadir a Campaña".
- Desde una Lista: los creadores de una lista se pueden mandar a una campaña con "Añadir a Campaña".
- Importación CSV de creadores: con "Añadir varios" dentro de la campaña. (El CSV de Mi Base de Clientes es para contactos de la marca, no para creadores.)
Cada creador añadido crea/actualiza automáticamente un Contacto en /contacts y dispara en segundo plano una captura inmediata de su contenido reciente (solo se guarda lo que cumple las reglas de la sección 12). Solo los creadores que son MIEMBROS de la campaña se rastrean.
En Elegir se ve por creador: seguidores, engagement, plataforma, Creator Score, estado del pipeline, fee acordado, toggles "Derechos Ads / Spark Ads" y "Exclusividad", email, portfolio, "Invitar a conectar" (envía al creador un enlace para conectar su Instagram profesional y obtener métricas reales), "Quitar de campaña", y la fila de compromisos: "Entregables comprometidos", "Enlace con UTM" y clics (sección 7). Los campos vacíos no se muestran a quien no edita.

### Paso 3 — Estados del pipeline (por creador dentro de la campaña)
8 estados, en este orden: Prospecto (PROSPECT) → Contacto (OUTREACH) → Negociando (NEGOTIATING) → Acordado (AGREED) → Contratado (CONTRACTED) → Envío (SHIPPING) → Publicado (POSTED) → Completado (COMPLETED).
Se cambian desde la pestaña Elegir (selector de estado), desde Ejecutar → Pipeline (kanban arrastrando) o desde el Pipeline global (/pipeline). Los creadores en estado Envío aparecen en Ejecutar → Envíos, donde se rellenan los datos de envío (nombre, dirección, ciudad, CP, país, teléfono, producto/SKU, cantidad) y se descarga el "CSV Envíos". La primera vez que un creador pasa a Acordado (o a cualquier estado posterior) se anota la fecha de cierre del acuerdo y, con el rastreo que se dispara en ese momento, se congela su línea base (sección 7).

### Paso 4 — Pagar (pestaña "Pagar")
Introducir el "Fee Acordado (€)" de cada creador y el formato negociado (Instagram: Post, Reel o Story; TikTok: Vídeo; YouTube: Integración, Dedicado o Short). La plataforma muestra el Análisis de Pricing por Influencer en cuatro bloques separados a propósito: (1) Benchmark de fee — dónde cae el fee frente a p25/p50/p75/p90 del mercado para su plataforma × tier × formato, con las etiquetas p25 "Buen precio", p50 "Precio de mercado", p75 "Máximo justificable" y p90 "Excepcional (solo con justificación)"; (2) CPM por formato × tier — fee ÷ vistas MEDIANAS del formato × 1000, con semáforo verde/amarillo/rojo frente al CPM objetivo y al máximo aceptable de ese formato y tier (el CPM aceptable baja con el tier); (3) EMV — valor de medios ganado que se espera del contenido; (4) Modificadores comerciales — derechos, whitelisting, exclusividad, urgencia, crossposting, bundle y recurrencia, aplicados sobre el precio de mercado (p50) y desglosados uno a uno. Además: Deal Advisor (veredicto, rango de mercado, escenarios, tip de negociación), Señales de Riesgo e Inversión Total. Regla de oro: los seguidores SOLO determinan el tier; el precio se evalúa sobre las vistas medianas del formato. Todo en euros sin IVA ni comisión de agencia. Requiere haber añadido creadores en Elegir. Las campañas UGC muestran pagos y "Contenido Entregado" en lugar de CPM. Detalle de benchmarks, mercados y modificadores en la sección 15. El fee acordado es el "coste" del creador en todas las métricas (sección 5).

### Paso 5 — Ejecutar: captura de contenido (pestaña "Ejecutar")
Sub-pestañas: Media (posts, reels, carruseles, vídeos, shorts capturados), Stories (stories de Instagram capturadas antes de que expiren a las 24 h), Pipeline (kanban) y Envíos.
Captura automática: el servidor ejecuta tareas periódicas (definidas en src/instrumentation.ts) mientras la app está desplegada:
- track: cada 6 horas — captura de posts de las campañas activas (Apify).
- stories: cada 12 horas — captura de stories de Instagram SOLO de las creadoras en estado Acordado o posterior de las campañas activas cuya fecha incluye hoy (actor de pago por story). Las menciones en stories llegan además en tiempo real vía Meta.
- check-posts: cada 12 horas — detecta posts nuevos y envía notificaciones.
- meta-sync: cada 2 horas — sincroniza las cuentas de Instagram Business conectadas vía API oficial de Meta (gratis, sin consumir Apify) y vuelca en las campañas las publicaciones donde los creadores etiquetan a la marca. OJO: Meta NO expone las vistas de las cuentas de otros, así que un reel que llega por la etiqueta de la marca entra con 0 vistas; la plataforma completa automáticamente esas vistas con el dato público del reel (enriquecimiento con Apify) para que cuenten como audiencia real. El alcance, las impresiones, los guardados y los compartidos de ese reel siguen siendo del creador: solo llegan si él conecta su cuenta o aporta su captura de estadísticas ("Registrar estadísticas", Paso 5).
- check-deletions: cada 24 horas — detecta posts borrados por el creador (cumplimiento). Las publicaciones borradas NO desaparecen: se mantienen en los totales, se marcan como eliminadas y se cuentan aparte (sección 5).
- meta-token-refresh: cada 24 horas — renueva tokens de Meta que caducan en menos de 7 días.
- discovery: cada 12 horas — procesa la cola de descubrimiento de creadores.
- benchmarks: cada 30 días (y unos 40 min después de cada despliegue) — recalcula los benchmarks propios de la agencia a partir de los fees acordados en las campañas (ver sección 15, "Benchmarks propios"). Un ADMIN puede lanzarlo bajo demanda.
Captura manual: botón "Rastrear Ahora" en la cabecera de la campaña (también en Planificar y Elegir). Escanea hashtags, menciones, perfiles de los miembros y stories; al terminar muestra "Rastreo completado: N posts encontrados, N stories". Requiere que la campaña esté ACTIVA y que Apify esté configurado. Hay una ventana de deduplicación de 3 horas: si un objetivo se rastreó hace menos de 3 h, se omite.
Captura automática por evento (sin pulsar nada): al añadir un creador a la campaña (individual o con "Añadir varios") y cada vez que su estado pasa a Acordado, Contratado, Envío, Publicado o Completado, la plataforma rastrea su contenido reciente en segundo plano y guarda solo lo que cumple las reglas de la sección 12. Ese mismo rastreo congela la línea base del creador si aún no la tiene (sección 7).
"Añadir publicación por URL" (Ejecutar → Media): pega la URL de un post, reel o vídeo de un creador que sea MIEMBRO de la campaña; "Detectar desde la URL" identifica la plataforma; se descarga con Apify y se guarda con fuente "manual". Si la publicación está fuera de las fechas de la campaña o el autor no es miembro, se rechaza con un mensaje claro.
Stories registradas a mano: en Ejecutar → Stories, "Registrar Story" permite anotar una story de un miembro con sus Vistas, Alcance y Respuestas reales (fuente "manual"); el dato real manda sobre cualquier estimación y lo registrado a mano nunca lo elimina la revalidación.
"Registrar estadísticas" (por publicación, en Ejecutar → Media y Stories; solo agencia): es la vía para convertir en dato REAL lo que solo el creador puede ver. La PM sube la captura de pantalla de las estadísticas del creador (la pantalla "Insights" / "Estadísticas" de Instagram o TikTok de ESA publicación); la IA lee la imagen y propone alcance, impresiones, vistas, guardados, compartidos (y en stories, vistas y alcance); la PM revisa y CONFIRMA los valores antes de guardar. También se pueden teclear los valores a mano sin captura. Al guardar, la publicación pasa a tener audiencia real y sus cifras entran en la tasa de engagement, el CPM y los objetivos (sección 5). Cada dato lleva su fuente: "Estadísticas del creador" (captura leída y confirmada), "API del creador" (cuenta conectada vía Meta, sección 13) o "manual" (tecleado), con la fecha de captura y quién lo registró; el informe y la exportación muestran esa fuente. Un dato real registrado manda sobre cualquier estimación. Regla operativa (David): en el brief de cada campaña hay que pedir al creador, como ENTREGABLE, la captura de estadísticas de cada pieza a las 72 h de publicarla (en stories, antes de que caduquen a las 24 h), o pedirle que conecte su cuenta ("Invitar a conectar"); sin eso, el alcance y las impresiones de la campaña no existirán.
"Revalidar contenido" (Ejecutar → Media): vuelve a comprobar todo el contenido de la campaña contra las reglas (miembro + fechas + etiqueta/mención de la marca) y DESVINCULA lo que no cumple. No borra nada: el post deja de contar en la campaña pero sigue en la base de datos. El contenido manual siempre se conserva. Devuelve "conservados / desvinculados".
Etiquetas de contenido: en cada publicación la PM puede anotar Enfoque, Gancho y Beneficio de producto (sección 9). Son opcionales.
Aviso "no tiene cuentas objetivo ni hashtags: no se capturará contenido": aparece en la cabecera cuando la campaña no tiene Cuentas de Marca Objetivo ni hashtags. Sin objetivos NO se captura nada; se añaden en "Editar Campaña".
Filtros en Media: ordenar por Más Recientes, Más Likes, Más Comentados, Más Vistos, Más Compartidos, Más Guardados; filtrar por plataforma e influencer; "Cargar Más".
Sentimiento: en Aprender → Sentimiento, "Analizar Comentarios" escanea los comentarios de los posts de la campaña y clasifica positivo/negativo/neutro.
Cumplimiento: detecta posts eliminados y colaboraciones no declaradas (falta #ad / "Colaboración pagada") en campañas de pago.

### Paso 6 — Medir: Resumen de la ficha, informe y exportación
- El Resumen de la ficha muestra, con las definiciones de la sección 5 y a partir de la misma fuente única que el informe: vistas, tasa de engagement sobre audiencia real (o "Sin dato real"), audiencia real y, aparte y etiquetada, la estimada, impresiones reales (cuando existen), creadores que han publicado; EMV Básico (interno) y EMV Ampliado con la nota de cuántas stories llevan audiencia estimada; el Resumen de Costes con el coste (fees acordados) y el Ratio EMV; la tabla "Objetivos de campaña" (KPI · Objetivo · Resultado · Variación, sección 6) y "Resultados de negocio (aportados por el cliente)" (sección 8). La base de la audiencia de cada publicación (alcance real, impresiones, vistas o estimada) y la fuente de sus estadísticas se ven en el anexo de contenidos del informe y en la exportación.
- Informe: botón "Informe (PDF)" en la cabecera → /campaigns/[id]/report. Es el único formato aprobado de informe (sección 10). El PDF se obtiene con el botón "Exportar PDF" del propio informe, que imprime el informe en pantalla (diálogo del navegador → "Guardar como PDF").
- Exportación de datos: "Exportar CSV" y "Exportar JSON" (menú Exportar de la cabecera de la ficha; endpoint GET /api/campaigns/[id]/export?format=csv|json). No hay exportación PDF por esa vía: el PDF es el informe impreso. Salen de la misma fuente única e incluyen: RESUMEN, OBJETIVOS (KPI, Objetivo, Resultado, Variación %, Veredicto), RESULTADOS DE NEGOCIO (si el cliente aportó datos), RENDIMIENTO POR CREADOR (coste, entregables comprometidos, publicaciones, stories, eliminadas, vistas, interacciones, audiencia total/real/estimada, tasa de engagement sobre audiencia real, CPM sobre audiencia real, EMV, Ratio EMV, "Vs su habitual (x)", "Línea base n", clics del enlace), la lista de publicaciones con base de la audiencia (real/estimada), estado de borrado y etiquetas de contenido, y un bloque DEFINICIONES con las mismas definiciones de la sección 5 (la ER y el CPM sobre audiencia real; la estimada, informativa). Una celda vacía en Tasa de engagement o CPM significa "sin dato real", no cero.
- Cómo se calcula el EMV (decisión de David, sept. 2026): el CPM depende del tipo de contenido y se edita en Ajustes → Benchmarks → "Tasas EMV". Valores actuales (Instagram): post 10 €, reel 14 €, story 8 €; TikTok vídeo 8 €; YouTube vídeo 15 €, short 8 €. "EMV Básico" = solo audiencia (audiencia ÷ 1000 × CPM), cifra interna que el cliente no ve; "EMV Ampliado" = audiencia + clics + interacciones valoradas (like, comentario, compartido, guardado, con valores por plataforma), fórmula TKOC, y es el ÚNICO EMV que ve el cliente, etiquetado en el portal y en los informes como "Valor mediático equivalente (estimado)" (decisión 8A). Posts, reels y vídeos usan SOLO datos reales en el EMV (impresiones > alcance > vistas; nunca se estiman para el EMV). Las STORIES de Instagram no tienen vistas públicas: si la story no tiene vistas reales, su audiencia se ESTIMA como seguidores de la creadora × porcentaje por tier (Nano < 10K: 15 %, Micro 10K-50K: 10 %, Mid 50K-250K: 7 %, Macro 250K-1M: 5 %, Mega > 1M: 4 %), y cada story consecutiva de la misma creadora (menos de 3 h de diferencia) vale un 15 % menos que la anterior (factor 0,85). Ejemplo: creadora de 40.000 seguidores → 4.000 vistas estimadas → 4 × 8 € = 32 € por story; tres seguidas ≈ 82 €. Si hay vistas reales registradas, el dato real manda y además la herramienta aprende el ratio real de esa creadora (vistas ÷ seguidores) para sus siguientes stories. Los informes indican cuántas stories llevan audiencia estimada. Transparencia de la prima EMV: los CPM del EMV (post 10 €, reel 14 €, story 8 €) son la referencia de CPM de medios de pago en España (post 8 €, reel 7 €, story 5 €) multiplicada por una prima de creador (contenido nativo, confianza de la audiencia y permanencia); si el cliente pregunta por qué el EMV vale más que su CPM en Meta Ads, esa es la explicación. El EMV está cerrado: sus valores no cambian con los benchmarks de fees.
- Ratio EMV (decisión 9B): EMV Ampliado ÷ coste (fees acordados), mostrado como multiplicador ("×2,4"), nunca como porcentaje. NUNCA se llama ROI: el EMV es una estimación del coste equivalente en medios pagados, no representa ventas ni retorno. Aparece en el Resumen de Costes de la campaña, en Inicio (subtítulo de la tarjeta EMV), en Resultados (Comparar campañas), en el informe (solo en la vista de agencia), en el Playbook y en Repeat Radar; nunca en el portal. Si alguien pregunta por el "ROI de la campaña" hay que responder con el Ratio EMV y explicar la diferencia.
- La palabra ROI (y ROAS, CPA) se reserva para datos reales de negocio aportados por el cliente (sección 8); el único rótulo con esa palabra es "ROI (dato del cliente)". Esos datos no los verifica la agencia y nunca se derivan del EMV.

### Paso 7 — Portal de cliente (solo lectura)
Ver sección 11. Para dar acceso a un cliente: (1) crear la marca en Marcas, (2) asociar la campaña a esa marca al crearla, (3) en Marcas → "Usuario Marca (solo lectura)" vincular o invitar al usuario con rol Brand (Ajustes → Equipo → Invitar Miembro → rol Brand, y asignación de marca). Un ADMIN puede previsualizar el portal de una marca.

### Paso 8 — Aprender (pestaña "Aprender")
- Inteligencia de Campaña: puntuación según el objetivo elegido, señales semáforo y recomendaciones. Se alimenta de la misma fuente única de cálculo que la ficha.
- Playbook — Qué hacer a continuación: nota de campaña, Ratio EMV, creadores a repetir/evitar, formato con mejor rendimiento, dónde reasignar presupuesto. La sección "Aprendizajes y próximos pasos" del informe (sección 10) se genera a partir de este mismo Playbook y de la fuente única; la versión del cliente omite la nota, el veredicto del Ratio EMV, el peor creador, la lista a evitar y el consejo de presupuesto.
- Sentimiento de comentarios.
- Editar Campaña (incluye objetivos numéricos y, si están congelados, el motivo del cambio), Guardar como Plantilla, Datos de Envío.

## 5. DEFINICIONES ÚNICAS de métricas (David, 2026-09-05) — valen para toda la plataforma
Estas definiciones son las únicas válidas. Ficha de campaña, informe, portal del cliente, exportación CSV/JSON, panel de Inicio, Resultados (comparar), inteligencia y este asistente consumen UNA misma fuente de cálculo del servidor (computeCampaignOverview en src/lib/campaign-overview.ts, sobre src/lib/metrics.ts), que carga TODO el contenido de la campaña, nunca una página. Nadie recalcula con fórmulas propias: si dos pantallas discrepan es un error, no una definición distinta. El asistente tampoco recalcula: comenta las cifras que recibe.
- Interacciones = likes + comentarios + compartidos + guardados (en TikTok los guardados son "favoritos"). Siempre las cuatro; nunca solo likes + comentarios.
- Audiencia de UNA publicación, en este orden estricto: (1) alcance real; si no hay, (2) impresiones reales; si no hay, (3) vistas reales — los tres de cualquier fuente (API de Meta, Apify, estadísticas del creador registradas por la PM o registro manual); si no hay ningún dato real, (4) estimación, SIEMPRE ETIQUETADA como estimada y SOLO INFORMATIVA (nunca entra en la ER, en el CPM ni en los objetivos):
  · Stories de Instagram sin vistas: seguidores de la creadora × % por tier (Nano < 10K 15 %, Micro 10K-50K 10 %, Mid 50K-250K 7 %, Macro 250K-1M 5 %, Mega > 1M 4 %), con decaimiento 0,85 por cada story consecutiva (< 3 h) de la misma creadora; si la herramienta ya conoce el ratio real de esa creadora (vistas ÷ seguidores de stories con datos reales), usa ese ratio en lugar del % del tier. Es la misma estimación que usa el EMV de la story, así métricas y EMV nunca discrepan. Los % por tier y el decaimiento se editan en Ajustes → Benchmarks → "Tasas EMV".
  · Publicaciones (post, carrusel, reel, vídeo, short) sin alcance, impresiones ni vistas: seguidores × tasa por tier (Nano 25 %, Micro 18 %, Mid 12 %, Macro 9 %, Mega 6 %). Las tasas se editan en Ajustes → Benchmarks → "Tasas EMV" → "Publicaciones: alcance estimado (% de seguidores)". Esta estimación solo sirve para la audiencia total informativa y su desglose; no entra en la ER, en el CPM ni en los objetivos, y el EMV de posts y reels tampoco la usa (solo datos reales).
  · Sin datos y sin seguidores: la publicación no tiene base ("sin base") y se informa cuántas hay.
- Audiencia REAL = Σ de la audiencia de las publicaciones que tienen alcance, impresiones o vistas reales. Es la cifra que manda: la base de la tasa de engagement, del CPM real y del objetivo de alcance. Se informa cuántas publicaciones la sostienen ("N publicaciones con dato real") y su desglose por base (alcance, impresiones, vistas). Aparte se informan "alcance real" (Σ alcance) e "impresiones reales" (Σ impresiones) como cifras puras.
- Audiencia ESTIMADA = Σ de las estimaciones etiquetadas (stories por tier, publicaciones por tier). Es informativa: se muestra aparte, siempre con su etiqueta y con el número de publicaciones estimadas, y en el informe es una línea separada que la PM puede ocultar al cliente. Audiencia total = real + estimada, también informativa, siempre con el porcentaje que es estimado ("34 % estimado"). Ninguna cifra estimada se mezcla nunca con una real sin decirlo.
- Tasa de engagement (ER), decisión 4A = Σ interacciones de las publicaciones CON audiencia real ÷ Σ audiencia real × 100, sobre TODO el contenido de la campaña con dato real, nunca sobre una página o unos pocos posts. Las estimaciones NUNCA entran en el numerador ni en el denominador. Se indica cuántas publicaciones hay detrás de la cifra. Sin ninguna publicación con audiencia real → "Sin dato real" (se muestra "—"; nunca 0 %, nunca una ER sobre estimaciones). Si el usuario pide "la ER contando las stories estimadas", la respuesta es que esa cifra no existe en la plataforma por decisión de David.
- Coste de un creador = fee acordado; si no hay fee, el coste registrado (producto, envío…); si no hay ninguno, 0 y no cuenta. Coste de campaña = suma; se indica cuántos miembros tienen coste. Es la cifra que usan CPM real, Ratio EMV, CPA y ROAS.
- CPM real de campaña = coste ÷ audiencia REAL × 1000 (€ por mil). Sin coste o sin audiencia real → sin dato. Cifra interna; distinto del CPM de negociación del Paso 4 (fee ÷ vistas medianas del formato).
- EMV: Básico (interno) y Ampliado (el único visible al cliente, "Valor mediático equivalente (estimado)"). Ratio EMV = EMV Ampliado ÷ coste, mostrado "×2,4" y nunca como porcentaje; NUNCA se llama ROI. La palabra ROI solo existe como "ROI (dato del cliente)" (sección 8).
- Publicaciones borradas por el creador: se MANTIENEN en todos los totales (audiencia, interacciones, ER, EMV), se marcan como eliminadas y su número se informa aparte ("N publicaciones eliminadas por el creador"). Nunca se restan en silencio ni se ocultan.
- Evolución diaria (timeline): agrupa cada publicación por su día en hora de Madrid (Europe/Madrid), no en UTC; por día: publicaciones, likes, comentarios, vistas, interacciones y audiencia.
- Objetivos: comparación con tolerancia ±10 % (sección 6). El objetivo de alcance se juzga SOLO sobre la audiencia real; sin dato real, "Sin datos". Un objetivo no fijado no se compara ni se muestra.
- Qué es dato REAL hoy y qué no (estado de producción, sept. 2026): son reales los likes, los comentarios y las vistas de reels y vídeos (datos públicos vía Apify; los reels que llegan por la etiqueta de la marca vía Meta entran con 0 vistas y se completan automáticamente con el dato público). NO son públicos y solo el creador puede aportarlos: alcance, impresiones, guardados, compartidos y vistas de stories. Por eso las publicaciones de imagen, los carruseles y las stories no tienen audiencia real salvo que el creador la aporte, y hasta que la aporte la tasa de engagement de la campaña se apoya en los reels con vistas. Dos vías para tener esos datos: (a) pedir al creador en el brief, como entregable, la captura de estadísticas de cada pieza a las 72 h y registrarla con "Registrar estadísticas" (la IA la lee y la PM la confirma; fuente "Estadísticas del creador"), o (b) que el creador conecte su cuenta ("Invitar a conectar"; fuente "API del creador"). También existe la entrada manual. Cada dato real guarda su fuente, la fecha de captura y quién lo registró.
- Principio general: un dato que no se ha rellenado no se muestra en ningún sitio; un dato que la PM rellena sí se muestra. Los datos reales van primero; lo estimado va después, etiquetado y separable.
- PROHIBIDO (comportamiento antiguo, eliminado del código): usar los seguidores como "alcance"; estimar alcance como seguidores × ER; calcular la ER dividiendo por el alcance de unos pocos posts o solo con likes + comentarios; calcular la ER o el CPM sobre la audiencia total o estimada (definición 4C, sustituida por 4A el 5 de septiembre de 2026); llamar ROI a cualquier cifra basada en EMV; mostrar dólares. Si el usuario pregunta por alguna de estas fórmulas, explicar la definición vigente.

## 6. OBJETIVOS de campaña (decisión 1B)
- Al crear o editar una campaña son obligatorios: el objetivo (Notoriedad, Engagement, Tráfico web, Conversión/Ventas o Contenido/UGC; opcional solo en Social Listening) y al menos UN objetivo numérico mayor que 0 entre: Vistas, Alcance, Interacciones, ER objetivo (%) y CPM máximo (€ por 1.000 vistas). El servidor rechaza la creación sin ellos. Recomendaciones por objetivo: notoriedad → vistas y/o alcance más CPM máximo; engagement → interacciones y/o ER; tráfico → vistas y CPM máximo (los clics se registran por creador con enlaces con UTM); conversión → alcance y CPM máximo (las ventas y códigos los aporta el cliente); contenido → entregables por creador, más un mínimo de vistas o CPM máximo.
- Congelación: los objetivos se congelan al arrancar, es decir, la primera vez que la campaña está ACTIVA con al menos un objetivo numérico (las campañas nuevas nacen activas, así que normalmente se congelan al crearlas). Desde ese momento cualquier cambio de un objetivo numérico queda registrado en el historial de la campaña (fecha, quién, campo, valor anterior, valor nuevo y motivo, si se indicó); en Editar Campaña aparece un campo "motivo del cambio" cuando los objetivos ya están congelados. El asistente debe recordar que cambiar objetivos a mitad de campaña deja rastro.
- Tabla de objetivos ("Objetivos de campaña" en el Resumen de la ficha; "Objetivos" en el informe y en la exportación): KPI · Objetivo · Resultado · Variación. El resultado sale de la fuente única: Vistas = vistas reales; Alcance = audiencia REAL (alcance → impresiones → vistas reales; las estimaciones nunca cuentan, decisión 4A); Interacciones; ER = tasa de engagement sobre audiencia real; CPM = CPM real sobre audiencia real. Veredicto con tolerancia ±10 %: dentro de ±10 % "En objetivo"; ≥ +10 % "Por encima del objetivo"; ≤ −10 % "Por debajo del objetivo"; sin resultado (p. ej. objetivo de alcance sin ninguna publicación con dato real) "Sin datos". En el CPM máximo el signo se invierte (menos es mejor). Los objetivos no rellenados no aparecen en la tabla.
- El cliente nunca recibe el objetivo de CPM (depende del coste): su fila desaparece en el portal, en su informe y en la API que lo alimenta.

## 7. LIBRO DE COMPROMISOS y LÍNEA BASE por creador (decisiones 2 y 14A)
- En Elegir, cada creador tiene su fila de compromisos: "Entregables comprometidos" (número de piezas), "Enlace con UTM" (URL con utm_… del creador) y "clics" (introducidos a mano o por integración). La ficha muestra "Entregados N / M" comparando las piezas capturadas con las comprometidas (en verde cuando se alcanzan). Quien no edita solo ve los valores que existen. Los entregables comprometidos también los ve el cliente en el portal.
- Línea base = "lo habitual" del creador ANTES de publicar para nosotros: mediana de vistas y mediana de interacciones de sus últimas 12 publicaciones del mismo formato que el negociado (familia vídeo: reel/vídeo/short → se compara por vistas; familia estática: post/carrusel → se compara por interacciones), publicadas en los 180 días anteriores al cierre del acuerdo, excluyendo lo que ya pertenece a la campaña (etiqueta de la marca). Mínimo 6 publicaciones elegibles; con 8 o más se descartan la mayor y la menor para que un viral no arrastre la mediana. Se informa qué % de la muestra era contenido de marca. Las stories no tienen línea base (no hay histórico público).
- Se congela UNA sola vez, automáticamente, cuando el creador pasa a Acordado (o cualquier estado posterior), aprovechando el mismo rastreo de perfil que ya hace la captura de campaña: coste cero extra. Fuente "apify". Si no hay muestra suficiente (< 6), la línea base queda pendiente y la PM puede introducirla a mano a partir de las estadísticas del creador: formato, mediana de vistas, mediana de interacciones y, opcionalmente, n (fuente "manual"; solo agencia; se puede borrar para volver a dejarla pendiente).
- Comparación: se expresa como multiplicador sobre su habitual, p. ej. "×1,37 sobre su habitual" (vistas de la campaña ÷ mediana de vistas, o interacciones ÷ mediana de interacciones), indicando n y fuente. Aparece en la tabla de creadores del informe (columna "Vs su habitual", solo si algún creador tiene línea base) y en la exportación CSV/JSON por creador. Si el formato entregado no es de la misma familia que la línea base, no se compara. Es la respuesta correcta a "¿este creador ha rendido mejor de lo normal?": nunca comparar con sus seguidores ni con su ER de perfil.

## 8. RESULTADOS DE NEGOCIO aportados por el cliente (decisión 14A)
- Dónde: ficha → Resumen → "Resultados de negocio (aportados por el cliente)". La PM introduce lo que el cliente comunica: código promocional, canjes del código, ventas, leads, ingresos (€), fuente del dato (p. ej. "Informe Shopify del cliente", "GA4"), fecha del dato y notas. Aparte, un "ROI (dato del cliente)" con sus notas si el cliente comunica un retorno; es el único lugar de la plataforma donde aparece la palabra ROI y nunca se calcula a partir del EMV.
- Derivados, SOLO si existen sus insumos y hay coste: CPA por venta = coste ÷ ventas; CPA por lead = coste ÷ leads; ROAS = ingresos ÷ coste (se muestra como "2,10x"). Siempre etiquetados "aportado por el cliente". La agencia no los verifica y NUNCA se derivan del EMV.
- Si no hay ningún dato rellenado, la sección no aparece en la ficha ni en el informe. El cliente (portal e informe) ve los datos que él mismo aportó (Código promocional, Canjes del código, Ventas reportadas, Leads reportados, Ingresos reportados, Fuente, Fecha del dato, Notas) con el aviso "Cifras facilitadas por el cliente; la agencia no las verifica de forma independiente", pero no CPA ni ROAS, porque dependen del coste.
- Los clics de enlaces con UTM se registran por creador en el Libro de compromisos (sección 7), no aquí.

## 9. ETIQUETAS DE CONTENIDO por publicación (decisión 15A)
- En cada publicación de Ejecutar → Media la PM puede anotar: Enfoque (lista: Problema / solución, Tutorial, Unboxing, Testimonio, Humor, Comparativa, Día a día, Otro), Gancho (texto corto, ≤ 120 caracteres: el gancho de los 3 primeros segundos) y Beneficio de producto (≤ 120 caracteres).
- Son OPCIONALES: un campo vacío no se guarda ni se muestra. Solo ADMIN/EMPLOYEE editan. Se exportan en CSV/JSON. Sirven para sacar aprendizajes por tipo de pieza (qué enfoque o gancho funcionó mejor), no afectan a ninguna métrica.

## 10. INFORME de campaña (/campaigns/[id]/report) — decisión 16A
- Se abre con el botón "Informe (PDF)" de la cabecera de la ficha. Es el único formato aprobado de informe y sustituye a los antiguos "Ver informe" y "Exportar informe". El generador de PDF antiguo y su ventana de "vista previa" YA NO EXISTEN: no hay que buscarlos.
- Maquetación: el informe está compuesto para imprimirse en A4 (una portada y luego secciones que respetan los saltos de página; las tarjetas y tablas no se parten entre páginas). Los datos REALES van siempre primero; todo lo estimado es una línea aparte, etiquetada "estimado", que la PM puede ocultar al cliente (decisión 4A).
- Contenido, en este orden: (1) Portada con el logo de The King of Content y el logo/nombre de la marca de la campaña (de la Marca asociada; sin marca solo aparece TKOC), subtítulo "Informe de resultados", fechas de la campaña. (2) "Resumen ejecutivo" con datos reales: tarjetas Influencers activados, Contenidos con sus stories, Vistas, Audiencia real (alcance → impresiones → vistas reales, con el número de publicaciones con dato real; debajo, la línea separada y ocultable "Audiencia estimada" con su etiqueta), Interacciones "likes + comentarios + shares + saves", Tasa de engagement sobre audiencia real (con cuántas publicaciones la sostienen; "Sin dato real" si no hay base), "Valor mediático equivalente (estimado)" con su definición, y la tabla "Objetivos" KPI · Objetivo · Resultado · Variación con veredictos "Por encima / En objetivo / Por debajo / Sin datos" y la nota "±10 %" (el alcance se juzga solo sobre audiencia real). (3) "Evolución" (publicaciones e interacciones por día, hora de Madrid). (4) "Contenidos destacados": las piezas con mejor resultado real (vistas e interacciones), con miniatura, creador, formato y enlace. (5) "Creadores" (seguidores, publicaciones, stories, audiencia real y, aparte, estimada, interacciones, ER sobre audiencia real, "Vs su habitual"). (6) "Aprendizajes y próximos pasos": aprendizajes generados automáticamente desde la fuente única (qué funcionó, creador y formato destacados, creadores a repetir, recomendación para la próxima campaña) más las conclusiones que escriba la PM; en la vista de agencia añade la nota de campaña, el veredicto del Ratio EMV, el peor creador, la lista a evitar y el consejo de presupuesto, que el cliente NUNCA ve. (7) "Datos": calidad de datos ("Datos reales: N publicaciones, X de la audiencia", "Estimado: N stories y M publicaciones sin datos", "Publicaciones retiradas por el creador: N"), fuentes de los datos (Apify, API de Meta, estadísticas del creador, manual) y "Resultados de negocio" (solo si el cliente aportó datos). (8) "Anexo": TODOS los contenidos de la campaña, por publicación: fecha, creador, formato, audiencia con su base — alcance real, impresiones, vistas o "~" estimado —, interacciones, fuente de las estadísticas; las publicaciones eliminadas por el creador llevan la insignia "Eliminado por el creador" y se cuentan aparte en una nota al pie. Todas las cifras salen de la misma fuente única que la ficha; si la PM oculta publicaciones o creadores, los totales del informe se recalculan en el servidor sin ellos para que cuadren con sus tablas.
- Panel de edición ("Editar informe", solo agencia, nunca se imprime): Título (sustituye al nombre de la campaña en portada y cabecera), Subtítulo (sustituye a "Informe de resultados"), Introducción (bajo "Resumen ejecutivo"), Conclusiones (dentro de "Aprendizajes y próximos pasos"), "Ocultar al cliente" por secciones y por columnas y tarjetas (entre ellas la línea de audiencia estimada y, en agencia, la columna CPM de creadores), y "Ocultar esta fila al cliente" en publicaciones y creadores concretos (marcados "Oculto al cliente"). Todo es opcional: sin tocar nada, el informe es el estándar. Los cambios se previsualizan en vivo hasta guardar.
- Cifras económicas en el informe: en la vista de agencia aparecen las columnas Coste y CPM de la tabla de creadores (se ocultan juntas con "Creadores · CPM est."), la tarjeta Ratio EMV, la fila del CPM máximo en Objetivos y CPA/ROAS. La versión del portal (/portal/campaigns/[id]/report) nunca las lleva. OJO: si la PM pulsa "Exportar PDF" desde su propia vista, el PDF incluye lo que ella ve; para un PDF sin cifras económicas hay que imprimirlo desde la versión del portal (o al menos ocultar la columna CPM antes).
- Versión enviada: "Marcar como enviado" (con nota opcional) → "Confirmar envío" registra versión 1, 2, 3… con fecha y quién la marcó; se muestra "Versión N enviada el … por …" (o "Aún no se ha marcado como enviado"). Sirve para saber qué vio el cliente y cuándo.
- PDF = botón "Exportar PDF" dentro del informe: imprime el informe en pantalla (diálogo del navegador → "Guardar como PDF"). Siempre se imprime en tema claro aunque la app esté en oscuro; los controles de edición no se imprimen. No existe otro generador de PDF.
- Exportación de datos: CSV y JSON desde el menú Exportar de la cabecera de la ficha (sección 4, Paso 6). No son el informe: son los datos.
- Versión para el cliente: el portal muestra el MISMO informe (/portal/campaigns/[id]/report) en modo portal, respetando lo que la PM ocultó y sin ninguna cifra económica (sección 11).

## 11. PORTAL DE CLIENTE: qué ve y qué no ve el cliente (rol BRAND)
Ve, solo lectura, dentro de /portal:
- Las campañas de su marca con su estado (En preparación, Activa, Pausada, Completada, Archivada).
- Dentro de cada campaña: el contenido capturado (posts, reels, stories, carruseles; las publicaciones eliminadas por el creador van marcadas), los creadores con su estado (Propuesto, Contactado, En conversación, Confirmado, Producto enviado, Contenido entregado, Publicado, Completado, Descartado), vistas, interacciones, audiencia real (y, cuando existen, alcance real e impresiones reales) con la audiencia estimada aparte y etiquetada, tasa de engagement sobre audiencia real ("Sin dato real" cuando no hay base) y entregables comprometidos.
- Los aprendizajes de la campaña en su versión para cliente: qué funcionó, creador y formato destacados, creadores a repetir y recomendación para la próxima campaña. Nunca la nota de campaña, el veredicto del Ratio EMV, el peor creador, la lista de creadores a evitar ni el consejo de presupuesto (todo eso es solo de agencia).
- Una sola cifra de valor: "Valor mediático equivalente (estimado)" (= EMV Ampliado) con su definición ("estimación del coste de una exposición e interacción equivalentes en medios pagados; no representa ventas ni retorno") y la nota de cuántas stories llevan audiencia estimada.
- "Ver informe completo": el mismo informe editable de la sección 10, con lo que la PM haya ocultado y sin columnas económicas.
- Los resultados de negocio que el propio cliente aportó (código, canjes, ventas, leads, ingresos), sin CPA ni ROAS.
- La tabla de objetivos sin la fila del CPM máximo.
NO ve nunca, ni en el portal ni en su informe ni en la API que lo alimenta: fees (acordado o pedido), coste, CPM (ni el real ni el objetivo de CPM máximo), Ratio EMV, EMV Básico, CPA, ROAS, benchmarks ni Deal Advisor. No puede editar, rastrear ni cambiar estados. Si un cliente pregunta por el "retorno", la respuesta en su lenguaje es el Valor mediático equivalente (estimado) y, si los aportó, sus propios resultados de negocio.

## 12. Reglas de captura de contenido (qué entra en una campaña y qué no)
0. Si la campaña no tiene Cuentas de Marca Objetivo ni hashtags, NO se captura nada (aviso en la cabecera). Primero hay que definir qué se rastrea.
1. Solo se captura contenido de creadores que son MIEMBROS de la campaña (añadidos en Elegir). Si un creador no está en la campaña, su contenido no se asocia aunque mencione a la marca.
2. Solo se captura contenido publicado DENTRO de las fechas de la campaña (desde Fecha de Inicio hasta el final del día de la Fecha de Fin, inclusive; sin fecha de fin = siempre activo). Posts anteriores al inicio no se asocian. El contenido sin fecha de publicación no se captura (no se puede demostrar que esté dentro de la ventana). Un mismo post cuenta en TODAS las campañas cuyas reglas cumpla (por ejemplo, en la campaña anual de contratos y en la mensual de ese mes): deciden la fecha y la pertenencia del creador, no el orden en que se capturó. En el panel de Inicio cada publicación se cuenta una sola vez.
3. El contenido debe estar relacionado con la marca: etiquetar/mencionar alguna de las Cuentas de Marca Objetivo (ej. @vileda.es) en el caption, las menciones o la etiqueta de colaboración, o usar alguno de los hashtags objetivo. Si el creador publica sin mencionar a la marca ni usar el hashtag, el post no se captura automáticamente.
4. Fuentes de datos, por prioridad: meta_api (API oficial de Meta, cuando la marca o el creador han conectado su Instagram Business; aporta alcance, impresiones, guardados y compartidos reales), apify (scraping público, fallback) y manual. Cada media registra su fuente, y esa fuente determina si su audiencia es real o estimada (sección 5).
5. Deduplicación: dentro de una campaña un post existe una sola vez (clave externalId + plataforma + campaña). Si Apify y Meta capturan el mismo post, se fusionan por el código corto del enlace y la fila conserva las métricas reales de Meta. El mismo post puede existir en varias campañas (una fila por campaña) y en los totales globales se cuenta una sola vez.
6. Filtro de país: si la campaña tiene país, se descarta el contenido de creadores que no encajan (heurística por bio, ubicación y ciudades para España).
7. Stories: solo Instagram; expiran a las 24 h. Dos vías: (a) rastreo automático cada 12 h SOLO de las creadoras en estado Acordado, Contratado, Envío, Publicado o Completado (el rastreo de stories se paga por story revisada, así que el PM DEBE marcar el estado cuando la creadora confirme; en Prospecto no se rastrean stories); (b) menciones en tiempo real vía Meta (Mensajería de Instagram): cuando una creadora menciona a @vileda.es con el sticker de una story, Instagram genera un mensaje "te ha mencionado en su story" y Meta avisa a la plataforma al instante; la story entra en la campaña sin coste, sea cual sea el estado de la creadora. Requiere que la cuenta de Instagram de la marca tenga activado "Permitir acceso a los mensajes" para la app (Configuración de Instagram → Privacidad → Mensajes → Herramientas conectadas) y que la creadora tenga cuenta pública (o siga a la marca). Las menciones en comentarios NUNCA cuentan como contenido de campaña. La story cuenta solo si menciona a la marca (sticker de mención o hashtag objetivo). Además, la PM puede registrar una story a mano con sus vistas, alcance y respuestas reales (Paso 5).
8. Las métricas por scraping (Apify) son públicas: likes, comentarios, vistas cuando el post las expone (reels y vídeos; los posts de imagen y los carruseles no tienen vistas públicas). Alcance, impresiones, guardados, compartidos y vistas de stories solo los tiene el creador: llegan con la conexión de SU cuenta (fuente "API del creador") o con su captura de estadísticas registrada por la PM ("Registrar estadísticas", fuente "Estadísticas del creador"), o a mano. Sin ninguno de esos datos, la audiencia de la publicación se estima, se etiqueta y queda fuera de la ER, del CPM y de los objetivos (sección 5).
8b. Reels que entran por la etiqueta de la marca vía Meta: Meta no expone las vistas de cuentas ajenas, así que llegan con 0 vistas; la plataforma completa esas vistas automáticamente con el dato público del reel para que cuenten como audiencia real. Si un reel sigue en 0 vistas tras el enriquecimiento (cuenta privada, reel borrado, cuota de Apify agotada), su audiencia se estima hasta que el creador aporte su captura.
9. Publicaciones borradas por el creador: el cron check-deletions las marca como eliminadas; siguen en los totales y se cuentan aparte (sección 5).

## 13. Conexión con Meta (Instagram Business) — Ajustes → Integraciones
- Botón "Conectar con Facebook" / "Conectar Instagram". Requisitos: cuenta de Instagram Profesional (Business o Creator) vinculada a una Página de Facebook, y permisos aceptados en el diálogo de Meta.
- Qué aporta: analíticas oficiales de posts, reels y stories (alcance, impresiones, guardados, compartidos) DE LA CUENTA CONECTADA, demografía de audiencia (edad, género, país, ciudad), y detección de menciones/etiquetas de marca en el contenido de los creadores sin capturas manuales. Matiz importante: la conexión de la MARCA trae las publicaciones en las que los creadores la etiquetan, pero Meta no da el alcance, las impresiones ni las vistas de las cuentas de otros; esos datos de una publicación del creador solo llegan si el propio creador conecta su cuenta (fuente "API del creador") o aporta su captura de estadísticas ("Registrar estadísticas"). Cuanto más contenido tiene dato real, más publicaciones sostienen la tasa de engagement y menor es la parte estimada (informativa) de la campaña.
- Permisos que pide la conexión de MARCA: instagram_basic, instagram_manage_insights, instagram_manage_comments, pages_show_list, pages_read_engagement, business_management. El permiso instagram_manage_comments es el que permite leer las publicaciones en las que los creadores ETIQUETAN a la marca (endpoint /tags); las conexiones hechas antes de añadirlo no lo tienen y hay que "Volver a conectar" (o reenviar a la marca el link de conexión IG) para que el contenido etiquetado entre en las campañas.
- Cada cuenta conectada se sincroniza automáticamente (cron meta-sync cada 2 h) y se puede "Sincronizar" manualmente. Estados: Conectado, Expirado (hay que "Volver a conectar"), Error, Desconectado. Los tokens se cifran en reposo (AES-256-GCM) y se renuevan automáticamente.
- Para que un CLIENTE conecte su Instagram sin cuenta en la herramienta: Marcas → "Copiar link de conexión IG" y enviárselo. El enlace caduca (30 días).
- Para que un CREADOR conecte su cuenta: en la campaña, pestaña Elegir → "Invitar a conectar" (email con enlace /creators/connect/[token]).
- Solo ADMIN gestiona integraciones. Otras integraciones en la misma pestaña: Apify (clave API, "Probar Conexión"), YouTube Data API v3 (clave API, datos públicos de canales y vídeos, sin OAuth), TikTok (OAuth configurado, pendiente de revisión de app). Prioridad de datos: APIs oficiales primero, Apify como fallback.

## 14. Apify (motor de scraping) y sus límites
- Apify se usa para: búsqueda en vivo de creadores, analizar perfiles, capturar posts/stories por scraping, hashtags y menciones, lookalikes por cuentas similares, y el rastreo de perfil del que sale la línea base del creador (sección 7).
- Tiene una CUOTA MENSUAL de uso. Cuando Apify devuelve "Monthly usage hard limit exceeded", la plataforma activa un cortacircuitos: todas las llamadas a Apify fallan al instante hasta que se reinicia el ciclo mensual (la fecha se lee de la API de Apify). Mientras tanto: no funciona Buscar en vivo, Analizar Perfil de creadores nuevos, ni la captura por scraping; SÍ sigue funcionando todo lo que viene de la API de Meta (meta-sync) y los datos ya guardados.
- Señales de que está agotado: banner en Creadores (/api/apify-status) y trabajos de rastreo fallidos.
- Solución: esperar al reinicio del ciclo o ampliar el plan en Apify; y priorizar la conexión de Meta de la marca/creadores para no depender del scraping.
- Ventana de deduplicación de 3 h por objetivo para no gastar cuota repitiendo rastreos.

## 15. Sistema de inteligencia (qué significan los indicadores)
- Creator Score (0-100, grado A+ a F): Calidad de Engagement 30 %, Eficiencia de Valor (CPM vs. mercado) 25 %, Consistencia 20 %, Historial de colaboraciones 15 %, Calidad de Audiencia 10 %.
- Deal Advisor: veredicto sobre el fee (buen trato / justo / sobrepagado) comparándolo con p25/p50/p75/p90 de su celda plataforma × tier × formato, rango de mercado ajustado por país, 3 escenarios (Conservador p25 "Buen precio", Realista p50 "Precio de mercado", Optimista p75 "Máximo justificable"; por encima del p90 solo "Excepcional (solo con justificación)"), ahorro/sobrecoste frente al p50 con los modificadores comerciales aplicados, tip de negociación.
- Señales de Riesgo (7 categorías, niveles crítico/aviso/info): caída de engagement, picos sospechosos de seguidores, borrado de contenido post-campaña, falta de disclosure (#ad), CPM muy por encima del mercado, baja tasa de entrega, anomalía engagement/seguidores.
- Repeat Radar: por creador con historial, recomienda Repetir / Considerar / Descartar. Su eje de coste es el Ratio EMV (EMV ÷ fee), nunca "ROI".
- Sistema de pricing (semilla "SPAIN 2026 v1", auditada con David en sept. 2026). Son CUATRO bloques separados a propósito y no se mezclan: (1) Benchmark de fee: ¿este fee es barato o caro frente al mercado? (p25/p50/p75/p90 por plataforma × tier × formato); (2) CPM por formato × tier: ¿qué CPM aceptamos por este formato y tier? (fee ÷ vistas medianas × 1000); (3) EMV: valor de medios ganado del contenido publicado (sección 4, Paso 6); (4) Modificadores comerciales: derechos, whitelisting, exclusividad, urgencia, crossposting, bundles, sobre el p50. Más el multiplicador de mercado por país y la mezcla con las negociaciones propias. Todo editable por ADMIN en Ajustes → Benchmarks (globales o por marca).
- Benchmark de fee (bloque 1): rangos p25/p50/p75/p90 en euros, sin IVA ni comisión de agencia. Formatos: Instagram Post, Reel y Story — la Story es UNA story; un pack de 3 stories = story × 2,5 —; TikTok solo Vídeo (ya no existe "Short" en TikTok); YouTube Integración, Dedicado (≈ 1,8 × integración) y Short (el antiguo formato "Vídeo" de YouTube equivale a Integración). Etiquetas de percentil: p25 "Buen precio", p50 "Precio de mercado", p75 "Máximo justificable", p90 "Excepcional (solo con justificación)". Los seguidores SOLO eligen el tier (Nano < 10K, Micro 10K-50K, Mid 50K-250K, Macro 250K-1M, Mega > 1M); nunca justifican por sí solos un precio. Ejemplos de p50 en España: Reel Instagram Micro 400 €, Mid 1.100 €, Macro 3.500 €; Vídeo TikTok Micro 250 €, Mid 650 €; Integración YouTube Mid 1.200 €.
- CPM aceptable por formato × tier (bloque 2): CPM = fee ÷ vistas MEDIANAS del formato × 1000 (nunca sobre seguidores). Cada formato × tier tiene un CPM objetivo (verde) y un CPM máximo (amarillo; por encima, rojo). El CPM aceptable BAJA con el tier porque las vistas se compran más baratas a escala: Reel Instagram objetivo/máximo Nano 40/60 €, Micro 30/45 €, Mid 22/32 €, Macro 16/24 €, Mega 12/18 €; Post Instagram Nano 45/65 € … Mega 14/22 €; Story Instagram Nano 40/60 € … Mega 16/25 €; Vídeo TikTok Nano 25/40 €, Micro 18/30 €, Mid 12/20 €, Macro 8/14 €, Mega 6/10 €; YouTube Integración Nano 30/45 € … Mega 20/30 €, Dedicado Nano 40/60 € … Mega 28/45 €, Short Nano 22/35 € … Mega 10/16 €.
- Mercados (multiplicador por país de la campaña o del creador, sobre los rangos de fee): España 1,0; Portugal 0,8; México 0,5; Colombia 0,4; Reino Unido 1,4; Alemania 1,3; Francia 1,3 (también Italia 1,0; Chile 0,5; Argentina 0,4; Perú 0,4; EE. UU. 1,6). Un Reel Mid p50 de 1.100 € en España son 550 € en México y 1.430 € en Reino Unido.
- Modificadores comerciales (bloque 4; se aplican sobre el precio de mercado p50, se SUMAN entre sí y se muestran desglosados para que la PM vea por qué se mueve la referencia): derechos de uso/paid media 30 / 90 / 180 días +20 / +40 / +70 %, derechos perpetuos +120 %; whitelisting / Spark Ads (la marca pauta desde el perfil del creador) +40 %; exclusividad de categoría 30 días / 90 días / 12 meses +25 / +50 / +100 %; urgencia (entrega en menos de 7 días) +25 %; crossposting en una segunda plataforma +25 %; bundle de 3 o más piezas −15 %; colaboración recurrente de 6 meses o más −25 %. Ejemplo: p50 1.100 € con derechos 90 días y whitelisting → 1.100 × (1 + 0,40 + 0,40) = 1.980 €.
- Benchmarks propios (las negociaciones de la agencia se convierten en el benchmark con el tiempo): cada fee acordado en una campaña es un dato. Un recálculo mensual (cron benchmarks; también bajo demanda por un ADMIN) agrupa los fees acordados por plataforma × tier × formato (tier por seguidores del creador; formato negociado o, si falta, el formato mayoritario del contenido entregado en esa campaña), los normaliza a España dividiendo por el multiplicador de mercado, recorta el 5 % de cada extremo y calcula p25/p50/p75/p90 y CPM propios (fee ÷ vistas medias del creador × 1000). La mezcla con la semilla es por contracción: mezcla = (n × propio + k × semilla) / (n + k) con k = 10, es decir, 10 negociaciones pesan tanto como la semilla; hacen falta al menos 20 negociaciones en una celda para considerarla benchmark interno, por debajo los datos propios solo matizan la semilla. Se guarda también el descuento de negociación (mediana de (fee pedido − fee acordado) ÷ fee pedido) cuando el fee pedido está registrado. Guarda anti-sesgo: solo cuentan acuerdos en estado Acordado o posterior y de los últimos 24 meses; cada acuerdo lleva la marca de la campaña como cliente y una celda solo mueve la semilla si sus acuerdos vienen de al menos 3 clientes distintos y tienen dispersión real de precios (la n se descuenta por concentración: n × (1 − HHI)). Un programa de una sola marca a tarifa fija (p. ej. 105 micros a 100 €) aparece en Ajustes como información pero NO altera el benchmark: es una lista de precios de un cliente, no el mercado. Además: solo campañas de tracking de influencers (los pagos UGC compran producción, no un post); el formato de cada acuerdo es el negociado en la ficha o, si falta, el entregado solo cuando es inequívoco (una pieza de un formato: un reel + 3 stories o dos reels se descartan porque el fee es del paquete); por debajo de 20 negociaciones efectivas la celda no mueve la semilla; y los percentiles propios se acotan entre 0,25× y 4× la semilla para que un fee mal tecleado no reescriba el mercado.
- Tiers por seguidores: Nano < 10K, Micro 10K-50K, Mid 50K-250K, Macro 250K-1M, Mega > 1M. (En la sugerencia de Creator Mix se agrupan como Micro < 10K, Mid 10K-100K, Macro 100K-1M, Mega > 1M; en Resultados, como Nano < 10K, Micro 10-100K, Mid 100-500K, Macro 500K-1M, Mega > 1M.)
- Engagement de perfil de un creador (para elegirlo): > 3 % bueno, > 5 % excelente; calidad de audiencia Alta > 3 %, Media 1-3 %, Baja < 1 %. No confundir con la tasa de engagement de campaña de la sección 5.
- Encaje con España (Spain Fit): "España confirmado", "España probable", "España parcial", "Hispano global" según bio, ubicación y señales.

## 16. Calculadora de Precios (/pricing)
Inputs: plataforma, seguidores, vistas medias (obligatorios; o un username para cargarlos "De BD"), fee que pide el creador, formato (Instagram Post / Reel / Story — la Story es una sola; pack de 3 = × 2,5 —; TikTok Vídeo; YouTube Integración / Dedicado / Short), y opcionales likes medios, comentarios, engagement rate, país del mercado y condiciones comerciales (derechos, whitelisting, exclusividad, urgencia, crossposting, bundle, recurrente).
Outputs: tier detectado (solo por seguidores), posición del fee frente a p25/p50/p75/p90 de su celda plataforma × tier × formato con las etiquetas "Buen precio" / "Precio de mercado" / "Máximo justificable" / "Excepcional (solo con justificación)", CPM real ("Coste por 1000 views" = fee ÷ vistas medias × 1000) frente al CPM objetivo y máximo de ese formato × tier, semáforo, Rango de Mercado ajustado por país, precio de referencia con los modificadores comerciales desglosados sobre el p50, Escenarios de Precio (Conservador p25 / Realista p50 / Optimista p75) con "Ahorro / Sobrecoste", Recomendación, "Decisión Final" y Tip de negociación. Avisos por tier (Macro/Mega nunca solo gifting; Nano suele aceptar gifting). Usa los mismos algoritmos y la misma configuración de benchmarks que Deal Advisor dentro de una campaña (incluida la mezcla con las negociaciones propias).

## 17. Similares (Lookalikes)
Introduce un @handle o la URL del perfil (instagram.com/usuario, tiktok.com/@usuario, youtube.com/@canal); la plataforma se detecta sola desde la URL. La plataforma toma el creador fuente (de la base de datos o analizándolo con Apify) y busca candidatos en la base de datos interna y, si Apify está disponible, en cuentas similares sugeridas por Instagram. Cada resultado tiene una puntuación de coincidencia con "Razones de coincidencia": categoría principal y categorías compartidas, similitud de seguidores, similitud de engagement, ubicación y marcas con las que ha trabajado. Desde el resultado: Ver perfil, Añadir a lista. Requiere Apify para buscar fuera de la base de datos.

## 18. Mi Base de Clientes y captura en vivo (/client-base)
- Contactos: importa clientes de la marca por CSV (con mapeo de columnas), manualmente o desde CRM (HubSpot/Apollo). Campos: nombre, email, empresa, dominio, teléfono, redes sociales, tipo de relación (cliente, lead, proveedor, partner, ex cliente, empleado), estado.
- Matches: el motor cruza los contactos con perfiles de creadores para encontrar "oportunidades warm": creadores que ya son clientes. Cada match tiene nivel de confianza (Exacto, Probable, Posible) y Warm Score con grado A-F (A ≥ 80, B ≥ 60, C ≥ 40, D ≥ 20) y tasa de respuesta esperada; se puede Confirmar o Rechazar.
- Capturas en Vivo y Widgets: crea un widget (nombre de marca, logo, color, textos, disparador: intención de salida / retardo / scroll / manual, dominios permitidos), copia el código de inserción (script antes de </body>) en la web de la marca, y captura los perfiles sociales de los visitantes; cada 4 h se enriquecen y se cruzan con creadores.

## 19. Ajustes → Equipo y otros
- Equipo: invitar por email con rol (Admin, Employee, Brand), cambiar rol, eliminar; "Brand Assignments" para asignar marcas a empleados.
- Benchmarks (ADMIN): rangos de fees p25/p50/p75/p90 por plataforma × tier × formato, umbrales CPM (objetivo/máximo) por formato × tier, multiplicadores de mercado por país, modificadores comerciales y el bloque "Tasas EMV": "Tasas CPM (por 1.000 impresiones)" por tipo de contenido, valores por interacción, "% de seguidores que ven una story" por tier con su decaimiento por secuencia, y "Publicaciones: alcance estimado (% de seguidores)" por tier (la tasa con la que se estima la audiencia de posts/reels sin datos reales; sección 5); "Restaurar valores por defecto" (semilla SPAIN 2026 v1); selección de marca para benchmarks propios de una marca. Los benchmarks internos derivados de las negociaciones de la agencia se recalculan solos cada mes y se mezclan con la semilla (k = 10, mínimo 20 por celda, recorte 5 %; solo mueven la semilla las celdas con al menos 3 clientes distintos y sin tarifa fija).
- Facturación: plan actual y uso (informativo).
- Plantillas de campaña: se crean desde una campaña ("Guardar como plantilla") y se cargan en Nueva Campaña.
- Notas de campaña por creador, Historial de colaboraciones previas de cada creador, Duplicados (creadores repetidos entre campañas).

## 20. Limitaciones conocidas y problemas frecuentes (lista de comprobación)
- "No aparece contenido en la campaña": comprobar en este orden (0) la campaña tiene Cuentas de Marca Objetivo o hashtags (sin ellos no se captura nada); (1) el creador está en Elegir como miembro; (2) el post se publicó dentro de las fechas; (3) el post menciona/etiqueta la cuenta objetivo o usa el hashtag; (4) Apify configurado y sin cuota agotada (banner en Creadores); (5) pulsar "Rastrear Ahora" (si se rastreó hace < 3 h, se omite); (6) esperar al siguiente cron (6 h). Si la marca tiene Meta conectado, Sincronizar en Integraciones.
- "La tasa de engagement dice 'Sin dato real'" o "la audiencia real es muy baja": ninguna (o casi ninguna) publicación tiene alcance, impresiones o vistas reales: posts de imagen, carruseles y stories no tienen audiencia pública, y los reels etiquetados vía Meta pueden estar aún en 0 vistas. Soluciones, por orden: (1) pedir al creador la captura de estadísticas de cada pieza (a las 72 h; en stories antes de las 24 h) y registrarla con "Registrar estadísticas" (la IA la lee, la PM confirma); (2) que el creador conecte su cuenta ("Invitar a conectar"); (3) registrar a mano las vistas/alcance reales de las stories ("Registrar Story"). Para la próxima campaña: incluir la captura de estadísticas como entregable en el brief. La ER nunca se rellena con estimaciones.
- "La audiencia estimada es alta" o "el cliente no quiere ver estimaciones": la estimación es informativa y va siempre etiquetada; no entra en la ER, en el CPM ni en los objetivos. En el informe es una línea aparte que se puede ocultar al cliente desde "Editar informe"; lo que no se debe hacer es mezclarla con la real.
- "Un reel del creador aparece con 0 vistas": ha entrado por la etiqueta de la marca vía Meta, que no expone las vistas de cuentas ajenas; el enriquecimiento automático las completa con el dato público. Si sigue en 0 (cuenta privada, reel borrado, cuota de Apify agotada), pedir la captura al creador y registrarla.
- "La ficha y el informe (o el portal) muestran cifras distintas": no debería ocurrir, todas salen de la misma fuente de cálculo. La única diferencia legítima es que la PM haya ocultado publicaciones o creadores en el informe (sus totales se recalculan sin ellos) o que el cliente no vea las cifras económicas.
- "¿Dónde está Exportar informe / Ver informe / la vista previa del PDF / el Diagnóstico?": ya no existen. El informe es "Informe (PDF)" → /campaigns/[id]/report y su botón "Exportar PDF"; los datos se exportan en CSV/JSON; la inteligencia de la campaña está en Aprender.
- "Quiero un PDF sin coste, CPM ni Ratio EMV": imprimirlo desde la versión del portal (/portal/campaigns/[id]/report) o, al menos, ocultar "Creadores · CPM est." antes de exportar (sección 10).
- "Falta la línea base de un creador": todavía no ha pasado a Acordado, o tenía menos de 6 publicaciones del formato en 180 días; la PM puede introducirla a mano.
- "No puedo crear la campaña": falta el objetivo o al menos un objetivo numérico mayor que 0 (sección 6).
- Stories caducan a las 24 h: si no se capturan ese día, se pierden.
- Alcance, impresiones, guardados, compartidos y vistas de stories solo los tiene el creador: llegan con la conexión de SU cuenta vía Meta o con su captura de estadísticas ("Registrar estadísticas"); con Apify solo métricas públicas (likes, comentarios, vistas de reels y vídeos). La conexión de la marca trae el contenido etiquetado, no las métricas privadas de los creadores.
- TikTok: la integración OAuth está pendiente de revisión de app; los datos de TikTok llegan por Apify. YouTube: datos públicos vía YouTube Data API (clave API).
- Apify tiene cuota mensual; al agotarse se detiene la búsqueda en vivo y el scraping hasta el nuevo ciclo.
- El asistente de IA (TKOC AI) solo lo usa el equipo de la agencia (ADMIN/EMPLOYEE) y NO ejecuta acciones en la plataforma: explica cómo hacerlas y analiza los datos que ve. No borra, crea ni edita nada. Tampoco recalcula métricas con fórmulas propias: usa las cifras de la fuente única y sus definiciones (sección 5).
- El portal de cliente es solo lectura; los usuarios BRAND no pueden rastrear ni editar y nunca ven coste, CPM, Ratio EMV, EMV Básico, CPA ni ROAS.
- Solo ADMIN puede tocar Integraciones y Benchmarks.
`.trim()
